
steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
    - -c
    - |
        if [ -d ./networking] && [ -d ./cluster] ; then
          terraform -chdir=./networking init && terraform -chdir=./cluster init
        fi 


  - id: 'tf plan' 
    name: 'hashicorp/terraform:1.6'
    entrypoint: sh
    args:
    - -c
    - |
          if [ -d ./networking] && [ -d ./cluster] ; then
            terraform -chdir=./networking plan && terraform -chdir=./cluster plan
          fi

  - id: 'tf apply' 
    name: 'hashicorp/terraform:1.6'
    entrypoint: sh
    args:
    - -c
    - |
        if [ -d ./networking] && [ -d ./cluster] ; then
          terraform -chdir=./networking apply -auto-approve && terraform -chdir=./cluster apply -auto-approve
        fi
options:
  logging: CLOUD_LOGGING_ONLY