steps:
 - id: 'terraform init'
   name: 'hashicorp/terraform:1.6'
   entrypoint: sh
   args:
      - -c
      - |
           if [ -d ./networking ] && [ -d ./cluster ]; then
             terraform -chdir=./networking init && terraform -chdir=./cluster init
           fi 

 - id: 'terraform destroy'
   name: 'hashicorp/terraform:1.6'
   entrypoint: sh
   args:
      - -c
      - |
           if [ -d ./networking ] && [ -d ./cluster ]; then
            terraform -chdir=./cluster destroy -auto-approve && terraform -chdir=./networking destroy -auto-approve 
           fi 
options:
  logging: CLOUD_LOGGING_ONLY